config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: "users/registrations",
    sessions: "users/sessions",
    omniauth_callbacks: "users/omniauth_callbacks",
    passwords: "users/passwords"
    }

  root "static_pages#top"

  resource :profile, only: %i[edit show update]

  resources :users, only: %i[show]

  resources :diagnoses, only: %i[new create]
  get "diagnoses/result/:token", to: "diagnoses#show", as: :diagnosis_result

  resources :posts do
    resources :comments, only: %i[create destroy], shallow: true
    collection do
      get :search_products
    end
  end

  resources :likes, only: %i[create destroy]

  resources :notifications, only: %i[index update] do
    collection do
      patch :mark_all_as_read
    end
  end

  resources :bookmarks, only: %i[index create destroy]

  get "products/autocomplete", to: "products#autocomplete", as: :autocomplete_products

  resources :products, only: %i[index show]

  resources :categories, only: %i[index show], param: :slug do
    get "products", to: "categories#products", as: :products
    get "products/autocomplete", to: "categories#products_autocomplete", as: :products_autocomplete
    get "products/:id", to: "products#show", as: :product
  end

  namespace :admin do
    root "products#index"

    get "login", to: "user_sessions#new"
    post "login", to: "user_sessions#create"
    delete "logout", to: "user_sessions#destroy"

    resources :products
    resources :posts, only: %i[index destroy]
  end

  get "privacy", to: "static_pages#privacy"
  get "terms", to: "static_pages#terms"
  get "up" => "rails/health#show", as: :rails_health_check
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
end

app/controllers/diagnoses_controller.rb
class DiagnosesController < ApplicationController
  skip_before_action :authenticate_user!
  DIAGNOSIS_QUESTIONS = YAML.load_file(Rails.root.join("config/diagnosis_questions.yml"))["questions"]

  def new
    @questions = DIAGNOSIS_QUESTIONS
  end

  def create
    if unanswered_questions?
      @questions = DIAGNOSIS_QUESTIONS
      @selected_answers = diagnosis_params.to_h
      flash.now[:alert] = "未回答の設問があります。"
      render :new, status: :unprocessable_entity
      return
    end

    diagnoser = Diagnosis::SweetnessTypeProcessor.new(diagnosis_params)
    result = diagnoser.call

    sweetness_type = SweetnessType.find_by(sweetness_kind: SweetnessType.sweetness_kinds[result[:sweetness_kind].to_s])
    profile = SweetnessProfile.create!(
      user_id: current_user&.id,
      sweetness_type_id: sweetness_type&.id,
      sweetness_strength: result[:scores][:sweetness_strength],
      aftertaste_clarity: result[:scores][:aftertaste_clarity],
      natural_sweetness: result[:scores][:natural_sweetness],
      coolness: result[:scores][:coolness],
      richness: result[:scores][:richness],
    )
    if current_user
      current_user.update(sweetness_type_id: profile.sweetness_type_id)
      SweetnessTwins::Updater.new(current_user).update_twins
      SweetnessTwins::Badge.new(current_user).refresh_twin_badges
    end
    redirect_to diagnosis_result_path(profile.token)
  end

  def show
    @profile = SweetnessProfile.find_by!(token: params[:token])
    @sweetness_kind = @profile.sweetness_kind

    set_meta_tags(helpers.diagnosis_meta_tags(@profile))
  end

  private

  def unanswered_questions?
    return true if params[:diagnosis].blank?

    required_keys = DIAGNOSIS_QUESTIONS.map { |q| q["category"] }
    required_keys.any? { |key| diagnosis_params[key].blank? }
  end

  def diagnosis_params
    params.fetch(:diagnosis, {}).permit(
      :sweetness_strength,
      :aftertaste_clarity,
      :natural_sweetness,
      :coolness,
      :richness
    )
  end
end

app/views/diagnoses/new.html.erb
<div class="p-1 md:p-4">
  <div class="flex flex-col p-1 items-center justify-center w-full max-w-4xl mx-auto bg-base-100 rounded-4xl">
    <h1 class="text-center text-lg md:text-xl border-b border-base-200 w-full p-2 md:p-4">
      <%= t('.title') %>
    </h1>

    <%= form_with url: diagnoses_path, method: :post, local: true, scope: :diagnosis do |f| %>
      <div class="py-4 px-2 md:px-8 w-full">
        <div class="mb-2 text-center">
          <% t("diagnoses.new.descriptions").each do |desc| %>
            <p class="mb-1 text-sm md:text-base"><%= desc %></p>
          <% end %>

          <% unless user_signed_in? %>
            <div class="text-sm text-base-300 text-center pt-4 leading-relaxed">
              <div class="inline-flex flex-wrap items-center justify-center gap-1">
                <span class="inline-flex items-center gap-1 whitespace-nowrap">
                  <span class="bg-info rounded-4xl p-1 inline-flex items-center gap-1 text-sm text-neutral">
                    <%= image_tag "handshake.svg", class: "h-5 w-5" %>
                    甘さツイン
                  </span>
                </span>
                <span class="inline-flex items-center gap-1 text-sm">
                  <div class="dropdown dropdown-top dropdown-right dropdown-hover">
                    <div tabindex="0" role="button" class="btn btn-xs btn-white btn-circle">?</div>
                    <ul tabindex="0" class="dropdown-content menu bg-base-100/90 text-base-300 rounded-box z-1 w-32 p-0.5 shadow-sm text-xs">
                      <li><a><%= t('defaults.dropdown.twins_description') %></a></li>
                    </ul>
                  </div>
                  <span class="whitespace-nowrap sm:whitespace-normal">の判定および</span>
                </span>
                <span class="whitespace-nowrap">
                  診断結果を記録するには
                </span>
              </div>
              <div class="text-sm">
                <%= link_to t('.sign_up'), new_user_session_path,
                class: "text-secondary hover:text-secondary underline" %>が必要です
              </div>
            </div>
          <% end %>
        </div>


        <div class="form-control text-left text-neutral p-1 md:p-2 w-full">
          <% @questions.each_with_index do |q, index| %>
            <div class="w-full max-w-md mx-auto px-2 py-4 md:p-3">
              
              <div class="label-text my-2 font-semibold md:text-base wrap-break-word">
                <span class="mr-2">Q<%= index + 1 %>.</span><%= q["question"] %>
              </div>
              
              <% if index == 0 %>
                <div class="w-full flex justify-center my-3">
                  <%= image_tag "diagnosis/pancake.webp", class: "w-full p-2 rounded-4xl" %>
                </div>
              <% end %>

              <% if index == 1 %>
                <div class="w-full flex justify-center my-3">
                  <%= image_tag "diagnosis/plate.webp", class: "w-full p-2 rounded-4xl" %>
                </div>
              <% end %>

              <% if index == 2 %>
                <div class="w-full flex justify-center">
                  <%= image_tag "diagnosis/assorted_fruits.webp", class: "w-full p-2 rounded-4xl" %>
                </div>
              <% end %>

              <% if index == 3 %>
                <div class="text-center text-sm text-stone-400">
                  <%= t('.example') %>
                </div>
                <div class="w-full flex justify-center my-3">
                  <%= image_tag "diagnosis/mint.webp", class: "w-full p-2 rounded-4xl" %>
                </div>
              <% end %>

              <% if index == 4 %>
                <div class="w-full flex justify-center my-3">
                  <%= image_tag "diagnosis/chocolate.webp", class: "w-full p-2 rounded-4xl" %>
                </div>
              <% end %>

              <div class="pt-1 space-y-1">
                <% q["options"].each do |opt| %>
                  <label class="label cursor-pointer flex items-start gap-2 text-neutral py-1 rounded-md md:hover:bg-stone-200 wrap-break-word">
                    <%= f.radio_button q["category"], opt["score"],
                        checked: (@selected_answers && @selected_answers[q["category"]] == opt["score"].to_s),
                        class: "radio radio-accent radio-xs mt-1" %>
                    <span class="whitespace-normal wrap-break-word"><%= opt["text"] %></span>
                  </label>
                <% end %>
              </div>
            </div>
          <% end %>

          <div class="text-center mt-3 pb-10 md:pb-4">
            <%= f.submit "診断する", class: "text-base btn btn-lg btn-accent" %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/diagnoses/show.html.erb
<div class="p-1 md:p-4">
  <div class="flex flex-col p-1 items-center justify-center w-full max-w-3xl mx-auto bg-base-100 rounded-4xl">
    <div class="text-center text-lg md:text-2xl p-2 md:p-4 border-b border-base-200 w-full">
      <%= t('.title') %>
    </div>
    <div class="text-sm sm:text-base leading-relaxed text-neutral text-center pt-3 sm:py-6">
      あなたの<span class="sm:hidden"><br></span><%=raw t('.sweetness_chart_completed') %>
    </div>
    <div class="px-2 py-4 sm:py-1 text-neutral">
      <div class="flex justify-center items-end flex-wrap gap-1 md:gap-2 text-base">
        <span class="text-left self-start">あなたは...</span>
        <span class="text-lg font-semibold bg-secondary text-center rounded-xl px-5 py-3 md:px-6 text-base-100 font-noto">
          <%= I18n.t("enums.sweetness_type.sweetness_kind.#{@profile.sweetness_kind}") %>
        </span>
        <span class="text-base text-neutral ml-auto md:ml-0">タイプ ✧*</span>
      </div>
    </div>

    <div class="flex w-full justify-end px-6 sm:px-30">
      <%= link_to "https://twitter.com/intent/tweet?url=#{root_url}diagnoses/result/#{@profile.token}&text=#{CGI.escape("【甘さ感覚診断結果】\n＼#{I18n.t("enums.sweetness_type.sweetness_kind.#{@profile.sweetness_kind}")}タイプ／でした！\n\n#甘さ感覚診断\n#あまピタ\n")}",
          target: "_blank",
          rel: "noopener noreferrer" do %>
        <span class="flex flex-row rounded-full bg-base-200 p-2 hover-animation">
          <%= image_tag "x-logo.svg", class: "h-6 w-6" %>
          <p class="pt-1 text-sm">でシェア</p>
        </span>
      <% end %>
    </div>

    <div class="flex justify-center p-4">
        <div class="w-full max-w-xs sm:max-w-md">
        <div class="p-2 border-secondary rounded-3xl bg-white/80 ring-2 ring-stone-200/50">
            <%= render "shared/chart/sweetness_profile_chart",
            chart_id: "radarChart",
            data: [
                @profile.sweetness_strength,
                @profile.aftertaste_clarity,
                @profile.natural_sweetness,
                @profile.coolness,
                @profile.richness,
            ] %>
        </div>
        </div>
    </div>

    <div class="flex flex-col items-center gap-4 pt-4 pb-12">
      <% if user_signed_in? %>
        <div class="flex flex-col sm:flex-row gap-4 sm:gap-2 w-full justify-center">
          <%= link_to posts_path(tab: :recommend), data: { turbo: false }, class: "text-center text-sm button-primary bg-info sm:flex-none hover-animation" do %>
            <span class="flex flex-row gap-1 justify-center">
              <%= image_tag "handshake.svg", class: "h-6 w-6" %>
              <%= t('.sweetness_twin_posts') %>
            </span>
          <% end %>
          <%= link_to categories_path, data: { turbo: false }, class: "text-center text-sm button-primary bg-success sm:flex-none hover-animation" do %>
            <span class="flex flex-row gap-1 justify-center">
              <%= image_tag "cookie.svg", class: "h-6 w-6" %>
              <%= t('.search_button') %>
            </span>
          <% end %>
        </div>
        <div class="flex justify-center w-full">
          <%= link_to new_diagnosis_path, data: { turbo: false }, class: "text-center text-sm button-primary bg-stone-200 hover-animation" do %>
            <span class="flex flex-row gap-1 justify-center">
              <%= t('.retake_diagnosis') %>
            </span>
          <% end %>
        </div>
      <% else %>
        <div class="flex flex-col sm:flex-row gap-4 sm:gap-2 w-full justify-center">
          <%= link_to posts_path, data: { turbo: false }, class: "text-center text-sm button-primary bg-info sm:flex-none hover-animation" do %>
            <span class="flex flex-row gap-1 justify-center">
              <%= image_tag "cookie.svg", class: "h-6 w-6" %>
              <%= t('.explore_reviews') %>
            </span>
          <% end %>
        </div>
        <div class="flex justify-center w-full">
          <%= link_to new_diagnosis_path, data: { turbo: false }, class: "text-center text-sm button-primary bg-stone-200 hover-animation" do %>
            <span class="flex flex-row gap-1 justify-center">
              <%= t('.retake_diagnosis') %>
            </span>
          <% end %>
        </div>
      <% end %>
    </div>

  </div>
</div>