config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: "users/registrations",
    sessions: "users/sessions",
    omniauth_callbacks: "users/omniauth_callbacks",
    passwords: "users/passwords"
    }

  root "static_pages#top"

  resource :profile, only: %i[edit show update]

  resources :users, only: %i[show]

  resources :diagnoses, only: %i[new create]
  get "diagnoses/result/:token", to: "diagnoses#show", as: :diagnosis_result

  resources :posts do
    resources :comments, only: %i[create destroy], shallow: true
    collection do
      get :search_products
    end
  end

  resources :likes, only: %i[create destroy]

  resources :notifications, only: %i[index update] do
    collection do
      patch :mark_all_as_read
    end
  end

  resources :bookmarks, only: %i[index create destroy]

  get "products/autocomplete", to: "products#autocomplete", as: :autocomplete_products

  resources :products, only: %i[index show]

  resources :categories, only: %i[index show], param: :slug do
    get "products", to: "categories#products", as: :products
    get "products/autocomplete", to: "categories#products_autocomplete", as: :products_autocomplete
    get "products/:id", to: "products#show", as: :product
  end

  namespace :admin do
    root "products#index"

    get "login", to: "user_sessions#new"
    post "login", to: "user_sessions#create"
    delete "logout", to: "user_sessions#destroy"

    resources :products
    resources :posts, only: %i[index destroy]
  end

  get "privacy", to: "static_pages#privacy"
  get "terms", to: "static_pages#terms"
  get "up" => "rails/health#show", as: :rails_health_check
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
end

app/models/notification.rb
class Notification < ApplicationRecord
  validates :action, presence: true
  validates :checked, inclusion: { in: [ true, false ] }

  belongs_to :sender, class_name: "User", foreign_key: "sender_id"
  belongs_to :recipient, class_name: "User", foreign_key: "recipient_id"
  belongs_to :notifiable, polymorphic: true

  enum :action, { liked: 0, commented: 1 }
  scope :unchecked, -> { where(checked: false) }
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  before_action :authenticate_user!

  def index
    @notifications = current_user.received_notifications
                                 .includes(
                                  :sender,
                                  :notifiable,
                                  sender: :avatar_attachment,
                                  notifiable: { post: :product }
                                 )
                                 .order(created_at: :desc)
    @pagy, @notifications = pagy(@notifications, limit: 12)
  end

  def update
    @notification = current_user.received_notifications.find(params[:id])
    @notification.update!(checked: true)
    redirect_to post_path(@notification.notifiable.post)
  end

  def mark_all_as_read
    current_user.received_notifications.unchecked.update(checked: true)
    redirect_to notifications_path
  end
end

app/helpers/notifications_helper.rb
module NotificationsHelper
  def notification_text_class(notification)
    notification.checked ? "text-stone-400" : "text-neutral"
  end
end

app/views/notifications/_notification.html.erb
<%= link_to notification_path(notification),
            data: { turbo_method: :patch, controller: "from-post" },
            class: "block w-full border-b border-base-200 px-1 sm:px-4 py-3 hover:opacity-80" do %>
  <div class="flex flex-row items-start gap-2 mb-1">
    <!-- アイコン -->
    <div class="shrink-0">
      <%= notification.sender.decorate.avatar_image(class: "size-8 md:size-10") %>
    </div>

    <!-- 通知文 -->
    <div class="flex-1 text-xs md:text-sm md:mt-2 leading-relaxed <%= notification_text_class(notification) %>">
      <span><%= notification.sender.name %></span>
      さんが
      <% if notification.notifiable_type == "Like" && notification.notifiable&.post %>
        あなたの投稿「<%= notification.notifiable.post.product.name %>」にいいねしました。
      <% elsif notification.notifiable_type == "Comment" && notification.notifiable&.post %>
        あなたの投稿「<%= notification.notifiable.post.product.name %>」にコメントしました。
      <% else %>
        <%= t('.no_posts') %>
      <% end %>
    </div>
  </div>

  <!-- 作成日時 -->
  <div class="flex justify-end text-sm mt-1 <%= notification_text_class(notification) %>">
    <time class="text-xs">
      <%= l notification.created_at, format: "%-m月%-d日 %H:%M" %>
    </time>
  </div>
<% end %>

app/views/notifications/index.html.erb
<div class="p-1 md:p-4">
  <div class="flex flex-col p-1 items-center justify-center w-full max-w-3xl mx-auto bg-base-100 rounded-4xl">
    <h1 class="text-center text-lg md:text-xl p-2 md:p-4 border-b border-base-200 w-full">
      <%= t('.title') %>
    </h1>

    <% if @notifications.present? %>
    <div class="flex flex-col items-center max-w-2xl p-1 md:py-2 md:px-10">
      <div class="flex flex-col w-full items-end p-1">
        <%= link_to t('.mark_all_as_read'),
            mark_all_as_read_notifications_path,
            data: { turbo_method: :patch },
            class: "btn btn-sm btn-outline btn-secondary" %>
      </div>
        <%= render @notifications %>
      </div>
      <div class="m-4">
        <%== pagy_nav(@pagy) %>
      </div>
    <% else %>
      <div class="p-6 text-base">
        <%= t('.no_notifications') %>
      </div>
    </div>
    <% end %>
  </div>
</div>