config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: "users/registrations",
    sessions: "users/sessions",
    omniauth_callbacks: "users/omniauth_callbacks",
    passwords: "users/passwords"
    }

  root "static_pages#top"

  resource :profile, only: %i[edit show update]

  resources :users, only: %i[show]

  resources :diagnoses, only: %i[new create]
  get "diagnoses/result/:token", to: "diagnoses#show", as: :diagnosis_result

  resources :posts do
    resources :comments, only: %i[create destroy], shallow: true
    collection do
      get :search_products
    end
  end

  resources :likes, only: %i[create destroy]

  resources :notifications, only: %i[index update] do
    collection do
      patch :mark_all_as_read
    end
  end

  resources :bookmarks, only: %i[index create destroy]

  get "products/autocomplete", to: "products#autocomplete", as: :autocomplete_products

  resources :products, only: %i[index show]

  resources :categories, only: %i[index show], param: :slug do
    get "products", to: "categories#products", as: :products
    get "products/autocomplete", to: "categories#products_autocomplete", as: :products_autocomplete
    get "products/:id", to: "products#show", as: :product
  end

  namespace :admin do
    root "products#index"

    get "login", to: "user_sessions#new"
    post "login", to: "user_sessions#create"
    delete "logout", to: "user_sessions#destroy"

    resources :products
    resources :posts, only: %i[index destroy]
  end

  get "privacy", to: "static_pages#privacy"
  get "terms", to: "static_pages#terms"
  get "up" => "rails/health#show", as: :rails_health_check
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
end

app/views/shared/_alert.html.erb
<div id="alert-message" 
     data-controller="fade" 
     role="alert"
     class="alert fixed top-25 left-4 w-fit flex items-center gap-2 p-2 bg-error text-sm md:text-base text-neutral rounded-full z-10 opacity-0 transition-opacity duration-500">
  <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 shrink-0 stroke-current" fill="none" viewBox="0 0 24 24">
    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
          d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
  </svg>
  <span><%= alert %></span>
</div>

app/views/shared/_average_chart.html.erb
<canvas id="averageChart" width="400" height="400"></canvas>

<script>
  document.addEventListener("turbo:load", function () {
    const ctx = document.getElementById("averageChart");
    if (!ctx) return;

    // 既存チャートを破棄（turboで複数回ロードされる対策）
    if (Chart.getChart(ctx)) {
      Chart.getChart(ctx).destroy();
    }

    // 画面幅でborderWidthを切り替え
    const borderWidth = window.innerWidth < 768 ? 2 : 4;
    new Chart(ctx, {
      type: 'radar',
      data: {
        labels: ["甘みの強さ", ["後味のキレ/","スッキリ感"], "自然な甘さ", "爽快感", "甘さの深み/コク"],
        datasets: [
          {
            label: "あなたの評価",
            data: [<%= user_data.map(&:to_i).join(", ") %>],
            backgroundColor: 'rgba(245, 182, 199, 0.4)',
            borderColor: 'rgba(245, 182, 199, 0.6)',
            borderWidth: borderWidth,
            pointBackgroundColor: 'rgba(245, 182, 199, 0.6)'
          },
          {
            label: "みんなの評価",
            data: [<%= average_data.map(&:to_i).join(", ") %>],
            backgroundColor: 'rgba(153, 215, 170, 0.4)',
            borderColor: 'rgba(153, 215, 170, 0.6)',
            borderWidth: borderWidth,
            pointBackgroundColor: 'rgba(153, 215, 170, 0.6)',
          }
        ]
      },
      options: {
        responsive: true,
        scales: {
          r: {
            min: 0,
            max: 5,
            ticks: {
              stepSize: 1
            }
          }
        }
      }
    });
  });
</script>

app/views/shared/_flash_messages.html.erb
<% flash.each do |type, message| %>
  <% if message.present? %>
    <%= render "shared/#{type}", "#{type}": message %>
  <% end %>
<% end %>

app/views/shared/_header.html.erb
<div class="navbar bg-base-100 fixed shadow-sm z-40 h-10 sm:h-12">
  <%= link_to root_path, class: "inline-block px-1 sm:px-2" do %>
    <%= image_tag "icon-logo.webp", class: "w-32" %>
  <% end %>

  <div class="ml-auto">
    <div class="drawer drawer-end z-50">
      <input id="my-drawer-4" type="checkbox" class="drawer-toggle" />
      <div class="drawer-content">
        <label for="my-drawer-4" class="btn btn-lg btn-square btn-ghost">
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" 
               viewBox="0 0 24 24" class="inline-block h-7 w-7 text-base-300 stroke-current"> 
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" 
                  d="M5 12h.01M12 12h.01M19 12h.01
                     M6 12a1 1 0 11-2 0 1 1 0 012 0zm7 0a1 1 0 11-2 0 1 1 0 012 0zm7 0a1 1 0 11-2 0 1 1 0 012 0z"></path>
          </svg>
        </label>
      </div>

      <div class="drawer-side z-50">
        <label for="my-drawer-4" aria-label="close sidebar" class="drawer-overlay"></label>
        <ul class="menu bg-base-100 text-base-content min-h-screen w-55 md:w-70 2xl:w-80 p-4">
          <% if user_signed_in? %>
            <li>
              <div class="flex items-center gap-3 p-2 md:p-4 pointer-events-none">
                <%= current_user.decorate.avatar_image(class: "w-10 h-10 md:w-15 md:h-15", loading: "lazy") %>
                <span class="text-xs md:text-sm"><%= current_user.name %></span>
              </div>
            </li>
            <li><%= link_to t('shared.header.mypage'), profile_path %></li>
            <li><%= link_to t('shared.header.logout'), destroy_user_session_path, data: { turbo_method: :delete } %></li>
          <% else %>
            <li><%= link_to t('shared.header.login'), new_user_session_path %></li>
            <li><%= link_to t('shared.header.sign_up'), new_user_registration_path %></li>
          <% end %>
          <li><%= link_to t('shared.header.about'), root_path %></li>
            <div class="flex items-center my-4 pointer-events-none">
              <div class="grow border-t border-2 border-stone-200"></div>
            </div>
          </li>
          <li><%= link_to t('shared.header.diagnosis'), new_diagnosis_path %></li>
          <li><%= link_to t('shared.header.products'), products_path %></li>
            <div class="flex items-center my-4 pointer-events-none">
              <div class="grow border-t border-2 border-stone-200"></div>
            </div>
          <li><%= link_to t('shared.header.terms_of_service'), terms_path %></li>
          <li><%= link_to t('shared.header.privacy_policy'), privacy_path %></li>
          <li><%= link_to t('shared.header.contact'), "https://forms.gle/LLJvxhEZWpGxK1EV7",
                  target: "_blank",
                  rel: "noopener noreferrer" %></li>
          <div class="flex items-center my-4 pointer-events-none">
            <div class="grow border-t border-2 border-stone-200"></div>
          </div>
          <div class="flex justify-center items-center my-4 pointer-events-none">
            <li><%= t('shared.header.copyright') %></li>
          </div>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/shared/_loading.html.erb
<div id="page-loader"
     data-controller="loading"
     data-loading-target-selector="[data-loader-target]"
     class="fixed inset-0 z-50 flex justify-center items-center
            bg-black/5 p-4 pb-8 opacity-100 backdrop-blur-md transition-opacity duration-700 ease-in-out">
  <div class="flex flex-col justify-center items-center gap-6">
    <span class="animate-spin h-8 w-8 rounded-xl bg-success"></span>
    <span class="animate-bounce text-neutral font-medium tracking-wide">Loading ...</span>
  </div>
</div>

app/views/shared/_product_list.html.erb
<% if products.present? %>
  <% products.each do |product| %>
    <div class="relative w-full border-b border-stone-300 last:border-b-0 py-2">
      <div class="flex flex-row items-center p-1 sm:px-10">
        <!-- 画像 -->
        <figure x-data="{ imageLoaded: false }"
                x-init="imageLoaded = $el.querySelector('img')?.complete || false">
          <div x-cloak x-show="!imageLoaded" class="flex animate-pulse space-x-4">
            <div class="p-0.5 sm:py-4 sm:px-8">
              <div class="size-23 sm:size-30 rounded-xl bg-stone-300"></div>
            </div>
          </div>

          <div x-show="imageLoaded" x-transition>
            <div class="p-0.5 sm:py-4 sm:px-8">
              <%= product.decorate.product_image(
                    class: "size-23 sm:size-30",
                    "@load" => "imageLoaded = true",
                    "@error" => "imageLoaded = true"
                  ) %>
            </div>
          </div>
        </figure>

        <div class="flex-1 w-full flex flex-col items-center sm:items-start p-0.5 sm:p-1 pl-2">
          <div class="sm:py-1 w-full">
            <div class="flex justify-between items-start w-full">
              <p class="text-xs sm:text-sm text-base-300 text-center sm:text-left pb-0.5 pl-2 sm:pl-0 sm:pb-1">
                <%= product.manufacturer %>
              </p>

              <% if user_signed_in? %>
                <div class="absolute top-1 right-3 sm:top-5 sm:right-28">
                  <%= render 'products/bookmark_buttons', { product: product } %>
                </div>
              <% end %>
            </div>

            <%= product_link(category, product, class: "hover:opacity-70 w-full") do %>
              <p class="text-sm sm:text-lg text-center sm:text-left pt-1 pb-2 sm:pb-3 max-w-[200px] sm:max-w-xl">
                <%= product.name %>
              </p>
              <div class="absolute top-14 -right-1 sm:right-8 sm:top-20">
                <span class="gap-1">
                  <%= image_tag "arrow.svg", class: "h-6 w-6 ml-1" %>
                </span>
              </div>
            <% end %>
          </div>

          <% stats = product_stats&.dig(product.id) || { total_posts: 0, perfect_sweetness_count: 0 } %>

          <% if stats[:total_posts].positive? %>
            <div class="p-0.5">
              <div class="flex flex-row items-center sm:gap-1 w-fit justify-center sm:justify-start amapita-count-ring ring-primary mx-auto sm:mx-0">
                <%= image_tag "smiley-wink.svg", class: "size-6 sm:size-7" %>
                <p class="text-sm sm:text-base">
                  <%= t("defaults.label.stats", count: stats[:total_posts], perfect: stats[:perfect_sweetness_count]) %>
                </p>
              </div>
            </div>
          <% else %>
            <div class="p-0.5 sm:pl-6">
              <div class="flex flex-row items-center gap-0.5 sm:gap-1 w-fit justify-center sm:justify-start amapita-count-ring ring-stone-300/90 mx-auto sm:mx-0">
                <%= image_tag "smiley-blank.svg", class: "size-6 sm:size-7" %>
                <p class="text-xs sm:text-base"><%= raw t('defaults.label.no_rating') %></p>
              </div>

              <% if show_new_post_button?(product) %>
                <div class="mt-3 text-center">
                  <% if user_signed_in? %>
                    <%= link_to new_post_path(product_id: product.id),
                                class: "bg-info rounded-full px-3 py-2 sm:px-4 inline-flex items-center shadow-sm transition hover-animation gap-2" do %>
                      <%= image_tag "cookie.svg", class: "size-5 sm:size-6" %>
                      <span class="text-sm"><%= t('defaults.buttons.new_post') %></span>
                    <% end %>
                  <% else %>
                    <div class="bg-info rounded-full py-2 px-5 inline-flex items-center shadow-sm transition hover-animation gap-2 tooltip tooltip-top"
                        data-tip="<%= t('defaults.require_login') %>">
                      <%= image_tag "cookie.svg", class: "size-5 sm:size-6" %>
                      <span class="text-sm sm:text-base"><%= t('defaults.buttons.new_post') %></span>
                    </div>
                  <% end %>
                </div>
              <% end %>

            </div>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>

  <div class="flex items-center justify-center p-4">
    <%== pagy_nav(pagy) %>
  </div>
<% else %>
  <div class="flex flex-col justify-center gap-1 md:gap-5 p-2 md:p-4 items-center text-center text-xs md:text-sm">
    <%= image_tag "smiley-x-eyes-fill.svg", class: "size-15 md:size-18" %>
    <span><%= t('defaults.message.no_product') %></span>
    <span><%= t('defaults.message.search_suggestion') %></span>
  </div>
<% end %>

app/views/shared/_profile_tab.html.erb
  <% if @user.sweetness_profiles.present? %>
    <div class="w-full max-w-xl xl:w-1/2 flex flex-col pb-10 xl:pb-1 lg:pt-10">
  <% else %>
    <div class="w-full max-w-xl flex flex-col flex-none pb-10 xl:pb-1 xl:pt-2">
  <% end %>
    <div class="p-1 xl:px-1">
      <div class="tabs-border flex justify-center w-full">
        <a href="<%= profile_path(tab: 'posts') %>" 
           data-turbo="false"
           class="tab text-sm md:text-base text-accent hover:text-accent <%= 'tab-active' if active_tab == 'posts' %>">
          <%= t('profiles.tabs.posts') %>
        </a>
        <a href="<%= profile_path(tab: 'liked_posts') %>"
           data-turbo="false"
           class="tab text-sm md:text-base text-primary hover:text-primary <%= 'tab-active' if active_tab == 'liked_posts' %>">
          <%= t('profiles.tabs.liked_posts') %>
        </a>
      </div>

      <div class="w-full xl:min-h-[600px]">
        <% if active_tab == 'posts' %>
          <div class="border-3 border-accent bg-white/80 rounded-4xl w-full p-1">
            <div class="flex flex-col mx-auto items-center justify-center text-sm text-base-300 xl:text-base w-full">
              <% if posts.present? %>
                <%= render posts %>
                <div class="flex items-center justify-center p-4 sm:p-0">
                  <%== pagy_nav(pagy_posts, link_extra: 'data-turbo-action="replace"', params: { tab: 'posts' }) %>
                </div>
              <% else %>
                <p class="p-4 text-stone-400"><%= t('profiles.empty_states.no_posts') %></p>
              <% end %>
            </div>
          </div>
        <% elsif active_tab == 'liked_posts' %>
          <div class="border-3 border-primary bg-white/80 rounded-4xl w-full pb-1">
            <div class="flex flex-col mx-auto items-center justify-center text-sm text-base-300 xl:text-base w-full">
              <% if likes.present? %>
                <%= render "posts/liked_posts", posts: likes %>
                <div class="flex items-center justify-center p-4 sm:p-0">
                  <%== pagy_nav(pagy_likes, link_extra: 'data-turbo-action="replace"', params: { tab: 'liked_posts' }) %>
                </div>
              <% else %>
                <p class="p-4 text-stone-400"><%= t('profiles.empty_states.no_liked_posts') %></p>
              <% end %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>

</div>

app/views/shared/_user_basic_info.html.erb
<div class="pb-12 md:p-4">
  <div class="flex flex-col p-1 lg:p-2 w-full lg:max-w-5xl mx-auto bg-base-100 rounded-4xl">
    <h1 class="text-center text-xl md:text-2xl p-4 border-b border-base-200 w-full">
      <% if user == current_user %>
        <%= t('profiles.mypage') %>
      <% elsif controller_name == "users" && action_name == "show" %>
        <%= t('profiles.user_info') %>
      <% end %>
    </h1>

    <div class="relative">
      <!-- 編集 -->
      <% if user == current_user %>
        <%= link_to edit_profile_path, class: "absolute top-2 right-14 md:right-52 lg:right-76 ring-2 ring-base-200 rounded-xl bg-stone-200 duration-200 hover:brightness-96 p-1", data: { turbo: false } do %>
          <%= image_tag "pencil.svg", class: "h-6 w-6" %>
        <% end %>
      <% end %>

      <!-- ユーザー情報 -->
      <div class="flex justify-center items-center flex-col lg:flex-row lg:items-start w-full py-4">
        <%= render "shared/loading" %>
        <div class="p-3">
          <%= user.decorate.avatar_image(
                class: "size-15",
                data: { "loader-target": "true" }
              ) %>
        </div>

        <div class="flex flex-col justify-center items-center gap-2 md:gap-4 text-neutral lg:py-4 px-2">
          <div class="text-base md:text-lg w-full">
            <div class="flex flex-col items-center sm:items-start gap-2">
              <div class="flex items-center lg:items-start lg:w-full gap-4 pt-2">
                <span><%= user.name %></span>
              </div>
              <% if user_signed_in? && user != current_user && sweetness_twin?(user) %>
                <div class="flex flex-row gap-1 text-xs rounded-full items-start sm:items-center px-2 py-1 bg-info w-fit">
                  <%= image_tag "handshake.svg", class: "h-4 w-4" %>
                  <%= display_sweetness_twin_badge(user) %>
                </div>
              <% end %>
              <% if display_post_badge(user).present? %>
                <span class="flex flex-row gap-1 text-xs rounded-full px-2 py-1 bg-success items-center">
                  <%= image_tag "badge.svg", class: "h-5 w-5" %>
                  <%= display_post_badge(user) %>
                </span>
                <% if user == current_user %>
                <span class="text-sm">
                  <%= t('profiles.total_post', count: user.posts.publish.count) %>
                </span>
                <% end %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
    <% if user.self_introduction.present? %>
      <div class="flex justify-center p-6 sm:p-3">
        <div class="text-sm sm:text-base max-w-xs lg:max-w-md">
          <%= user.self_introduction %>
        </div>
      </div>
    <% end %>

    <div class="flex flex-col xl:flex-row justify-center items-center xl:items-start pb-4 w-full gap-4 lg:gap-2 xl:px-2">
      <!-- 甘さタイプラベル + チャート -->
      <% if sweetness_profiles.present? %>
        <div class="flex flex-col w-full lg:w-3/5 justify-start max-w-lg pt-4 xl:pt-0 flex-1 pb-3">
      <% else %>
        <div class="flex flex-col w-full justify-center sm:max-w-lg">
      <% end %>
      <!-- 甘さタイプ -->
      <% if sweetness_profiles.present? %>
        <div class="flex justify-center items-start font-bold py-2 w-full sm:pt-6 gap-2 font-noto">
          <p class="text-base-300 text-sm md:text-base pt-2"><%= t("activerecord.attributes.sweetness_type.sweetness_kind") %>：</p>
          <span class="rounded-xl bg-secondary text-white px-3 py-2 text-base">
            <%= I18n.t("enums.sweetness_type.sweetness_kind.#{sweetness_type.sweetness_kind}") %>
          </span>
          <% if user == current_user %>
            <p class="px-3">
            <%= link_to "https://twitter.com/intent/tweet?url=#{root_url}diagnoses/result/#{sweetness_profiles.token}&text=#{CGI.escape("【甘さ感覚診断結果】\n＼#{I18n.t("enums.sweetness_type.sweetness_kind.#{sweetness_type.sweetness_kind}")}タイプ／でした！\n\n#甘さ感覚診断\n#あまピタ\n")}",
                target: "_blank",
                rel: "noopener noreferrer" do %>
              <span class="flex flex-row rounded-xl bg-base-200 p-2">
                <%= image_tag "x-logo.svg", class: "h-6 w-6" %>
              </span>
            <% end %>
            </p>
          <% end %>
        </div>
        <!-- チャート -->
        <div class="p-2 lg:py-6 rounded-3xl bg-white/80 ring-2 ring-stone-200/50">
          <div class="mx-auto w-full max-w-md">
            <%= render "shared/chart/sweetness_profile_chart",
                chart_id: chart_id,
                data: [
                  sweetness_profiles.sweetness_strength,
                  sweetness_profiles.aftertaste_clarity,
                  sweetness_profiles.natural_sweetness,
                  sweetness_profiles.coolness,
                  sweetness_profiles.richness,
                ] %>
          </div>

          <div class="flex justify-end text-xs md:text-sm pb-4 text-base-200">
            <%= t('profiles.diagnosis.latest_date') %>：
            <%= l sweetness_profiles.created_at %>
          </div>

          <% if user == current_user %>
            <div class="flex justify-end pb-4">
              <%= link_to new_diagnosis_path, class: "text-sm bg-success button-primary hover-animation", data: { turbo: false } do %>
                <%= t('defaults.buttons.retake_diagnosis') %>
              <% end %>
            </div>
          <% end %>
        </div>
      </div>
    <% else %>
    <% if user == current_user %>
    <div class="flex justify-center pt-4 font-noto">
      <p class="text-base-300 text-sm md:text-base pt-2">
      <%= t('profiles.diagnosis_status') %>
    </div>
    <div class="text-center pt-6 text-sm text-stone-500 leading-relaxed">
      診断を行うと、<span class="md:hidden"><br></span>好みの甘さ感覚が近いユーザー<br>
      『 甘さツイン 』が判定され、<br>
        "ちょうど良い甘さ"の商品と<span class="md:hidden"><br></span>出会いやすくなります✧*
      </div>
      <div class="flex justify-center pt-6">
        <%= link_to new_diagnosis_path, class: "text-base text-neutral btn btn-accent", data: { turbo: false } do %>
          <%= t('defaults.buttons.take_diagnosis') %>
        <% end %>
      </div>
      <div class="flex flex-col justify-center mx-auto text-stone-400 items-center text-center text-sm py-6">
            <%= raw t('defaults.message.general_notice') %>
      </div>
  <% end %>
<% end %>

app/views/shared/_user_profile.html.erb
<div class="p-2 md:p-4">
  <div class="flex flex-col p-2 w-full max-w-3xl mx-auto bg-base-100 rounded-4xl">
    <h1 class="text-center text-xl md:text-2xl p-4 border-b border-base-200 w-full">
      <%= user == current_user ? t('profiles.show.title') : t('profiles.info') %>
    </h1>

    <!-- ユーザー情報 -->
    <div class="flex flex-col justify-center items-center sm:flex-row sm:items-start sm:gap-6 w-full py-4">
      <div class="md:p-4">
        <%= user.decorate.avatar_image(class: "w-15 h-15 md:w-20 md:h-20") %>
      </div>

      <div class="flex flex-col justify-center items-center gap-2 md:gap-4 text-neutral py-4 px-2">
        <div class="text-lg md:text-xl font-semibold break-words">
          <div class="flex flex-col items-start gap-2">
            <span><%= user.name %></span>
            <% if user_signed_in? && user != current_user && sweetness_twin?(user) %>
              <span class="flex flex-row gap-1 text-xs rounded-full items-center px-2 py-1 bg-info w-fit">
                <%= image_tag "handshake.svg", class: "h-4 w-4" %>
                <%= display_sweetness_twin_badge(user) %>
              </span>
            <% end %>
            <% if display_post_badge(user).present? %>
              <span class="flex flex-row gap-1 text-xs rounded-full px-2 py-1 bg-success">
                <%= image_tag "badge.svg", class: "h-5 w-5" %>
                <%= display_post_badge(user) %>
              </span>
              <span class="text-sm">
                <%= t('profiles.total_post', count: user.posts.count) %>
              </span>
            <% end %>
          </div>
        </div>

        <div class="text-sm md:text-base break-words max-w-[20ch] md:min-h-[1.5rem]">
          <%= user.self_introduction.presence || "" %>
        </div>

        <!-- 編集 -->
        <% if user == current_user %>
          <div class="flex w-full mt-2 justify-center sm:justify-end">
            <%= link_to edit_profile_path, class: "text-sm btn btn-outline btn-accent", data: { turbo: false } do %>
              <%= t('helpers.submit.edit') %>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>

    <!-- チャート -->
    <% if sweetness_profiles.present? %>
      <div class="flex justify-center md:p-2 w-full">
        <div class="w-full max-w-md md:max-w-lg p-2 rounded-3xl bg-white">

          <div class="flex justify-end text-sm md:text-base font-bold mb-2">
            <span class="rounded-xl bg-secondary text-white px-3 py-2 text-sm md:text-base">
              <%= I18n.t("enums.sweetness_type.sweetness_kind.#{sweetness_type.sweetness_kind}") %>
            </span>
          </div>

          <div class="mx-auto w-full max-w-md">
            <%= render "shared/chart/sweetness_profile_chart",
                chart_id: chart_id,
                data: [
                  sweetness_profiles.sweetness_strength,
                  sweetness_profiles.aftertaste_clarity,
                  sweetness_profiles.natural_sweetness,
                  sweetness_profiles.coolness,
                  sweetness_profiles.richness,
                ] %>
          </div>

          <div class="flex justify-end text-xs md:text-sm pb-4 text-base-200">
            <%= t('profiles.diagnosis.latest_date') %>：
            <%= l sweetness_profiles.created_at %>
          </div>

          <% if user == current_user %>
            <div class="flex justify-end">
              <%= link_to new_diagnosis_path, class: "text-sm btn btn-md btn-dash btn-primary hover-animation", data: { turbo: false } do %>
                <%= t('defaults.buttons.retake_diagnosis') %>
              <% end %>
            </div>
          <% end %>
        </div>
      </div>
    <% else %>
      <% if user == current_user %>
        <div class="text-center py-6 text-sm md:text-base text-base-200">
          <%= raw t('profiles.diagnosis.no_data') %>
        </div>
        <div class="flex justify-center">
          <%= link_to new_diagnosis_path, class: "text-sm btn btn-primary hover-animation", data: { turbo: false } do %>
            <%= t('defaults.buttons.take_diagnosis') %>
          <% end %>
        </div>
      <% end %>
    <% end %>

    <!-- タブ -->
    <div class="tabs tabs-border py-2 md:py-6 justify-center w-full">
      <!-- 投稿 -->
      <input type="radio" name="my_tabs_4" role="tab"
        class="tab text-xs md:text-base text-primary hover:text-primary"
        aria-label="<%= t('profiles.tabs.posts') %>" checked />
      <div role="tabpanel" class="tab-content md:p-6 border-primary bg-white rounded-4xl w-full">
        <div class="flex flex-col mx-auto items-center justify-center text-xs md:text-sm w-full">
          <% if @posts.present? %>
            <%= render @posts %>
              <div class="flex items-center justify-center p-4">
                <%== pagy_nav(@pagy_posts) %>
              </div>
          <% else %>
            <p class="p-4"><%= t('profiles.empty_states.no_posts') %></p>
          <% end %>
        </div>
      </div>

      <!-- ブックマーク -->
      <input type="radio" name="my_tabs_4" role="tab"
        class="tab text-xs md:text-base text-accent hover:text-accent"
        aria-label="<%= t('profiles.tabs.bookmarks') %>" />
      <div role="tabpanel" class="tab-content md:p-6 border-accent bg-white rounded-4xl w-full">
        <div class="flex flex-col mx-auto items-center justify-center text-xs md:text-sm w-full">
          <% if @bookmarks.present? %>
            <%= render "products/user_bookmarks", products: @products %>
              <div class="flex items-center justify-center p-4">
              <%== pagy_nav(@pagy_bookmarks) %>
            </div>
          <% else %>
            <p class="p-4"><%= t('profiles.empty_states.no_bookmarks') %></p>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>