config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: "users/registrations",
    sessions: "users/sessions",
    omniauth_callbacks: "users/omniauth_callbacks",
    passwords: "users/passwords"
    }

  root "static_pages#top"

  resource :profile, only: %i[edit show update]

  resources :users, only: %i[show]

  resources :diagnoses, only: %i[new create]
  get "diagnoses/result/:token", to: "diagnoses#show", as: :diagnosis_result

  resources :posts do
    resources :comments, only: %i[create destroy], shallow: true
    collection do
      get :search_products
    end
  end

  resources :likes, only: %i[create destroy]

  resources :notifications, only: %i[index update] do
    collection do
      patch :mark_all_as_read
    end
  end

  resources :bookmarks, only: %i[index create destroy]

  get "products/autocomplete", to: "products#autocomplete", as: :autocomplete_products

  resources :products, only: %i[index show]

  resources :categories, only: %i[index show], param: :slug do
    get "products", to: "categories#products", as: :products
    get "products/autocomplete", to: "categories#products_autocomplete", as: :products_autocomplete
    get "products/:id", to: "products#show", as: :product
  end

  namespace :admin do
    root "products#index"

    get "login", to: "user_sessions#new"
    post "login", to: "user_sessions#create"
    delete "logout", to: "user_sessions#destroy"

    resources :products
    resources :posts, only: %i[index destroy]
  end

  get "privacy", to: "static_pages#privacy"
  get "terms", to: "static_pages#terms"
  get "up" => "rails/health#show", as: :rails_health_check
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
end

app/models/product.rb
class Product < ApplicationRecord
  include ImageValidatable
  has_one_attached :image

  validates :name, presence: true, length: { maximum: 25 }
  validates :manufacturer, presence: true
  validates :name, uniqueness: { scope: :manufacturer, message: :name_manufacturer_taken }
  validates :category_id, presence: { message: :select }

  belongs_to :category, optional: true
  belongs_to :user
  has_many :posts, dependent: :destroy
  has_many :bookmarks, dependent: :destroy

  def self.full_manufacturer_list
    @full_manufacturer_list ||= I18n.t("products.manufacturers.list")
  end

  def self.main_manufacturers
    @main_manufacturers ||= full_manufacturer_list - [ "その他" ]
  end

  scope :manufacturer_other, -> {
    where.not(manufacturer: main_manufacturers)
  }

  def total_posts
    posts.publish.size
  end

  def perfect_sweetness_count
    posts.publish.where(sweetness_rating: Post.sweetness_ratings[:perfect_sweetness]).size
  end

  def average_sweetness_scores
    scores = PostSweetnessScore.where(post_id: posts.select(:id))
    {
      sweetness_strength: scores.average(:sweetness_strength),
      aftertaste_clarity: scores.average(:aftertaste_clarity),
      natural_sweetness: scores.average(:natural_sweetness),
      coolness: scores.average(:coolness),
      richness: scores.average(:richness)
    }
  end

  def self.ransackable_attributes(auth_object = nil)
    [ "name", "manufacturer" ]
  end

  def self.ransackable_associations(auth_object = nil)
    [ "category", "posts" ]
  end
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < Admin::BaseController
  def index
    @q = Product.ransack(params[:q])
    products_scope = @q.result(distinct: true)
                       .includes(
                         :image_attachment,
                         :category
                        )
                       .order(created_at: :desc)
    @total_count = products_scope.count
    @pagy, @products = pagy(products_scope)
    @products = @products.decorate
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    @product.user = current_user
    if @product.save
      redirect_to admin_products_path, notice: t("defaults.flash_message.registered", item: Product.model_name.human)
    else
      flash.now[:alert] = t("defaults.flash_message.not_registered", item: Product.model_name.human)
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    if @product.update(product_params)
      redirect_to admin_products_path, notice: t("defaults.flash_message.updated", item: Product.model_name.human)
    else
      flash.now[:alert] = t("defaults.flash_message.not_updated", item: Product.model_name.human)
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.image.purge if @product.image.attached?
    @product.destroy!
    redirect_to admin_products_path, notice: t("defaults.flash_message.deleted", item: Product.model_name.human)
  end

    private

  def product_params
    params.require(:product).permit(:name, :manufacturer, :category_id, :image, :product_url, :product_image_url)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  skip_before_action :authenticate_user!

  def index
    @q = Product.ransack(params[:q])
    products_result = @q.result(distinct: true)
                        .includes(:image_attachment)
                        .order(manufacturer: :asc, name: :asc)
    @pagy, @products = pagy(products_result)
    @product_stats = product_stats(@products)
  end

  def show
    @product = Product.find(params[:id]).decorate
    setup_product_details
  end

  def autocomplete
    query = params[:q]

    if query.blank?
      @products = Product.none
    else
      @products = Product.where("name ILIKE ? OR manufacturer ILIKE ?", "%#{query}%", "%#{query}%")
                        .select(:id, :name, :manufacturer)
    end

    respond_to do |format|
      format.html { render partial: "products/autocomplete_suggestions", locals: { products: @products } }
    end
  end

  private

  def setup_product_details
    published_posts = @product.posts.publish.includes(user: :avatar_attachment)

    if user_signed_in?
      @user_unpublish_post = @product.posts.unpublish.find_by(user_id: current_user.id)
    end

    @posts = published_posts.order(created_at: :desc)
    @unpublish_posts = @product.posts.unpublish
    @average_scores = @product.average_sweetness_scores
    @user_post = published_posts.find_by(user_id: current_user.id) if user_signed_in?

    @pagy, @posts = pagy(@posts, limit: 3)
  end
end

app/helpers/products_helper.rb
module ProductsHelper
  def show_reputation_button(post, user_unpublish_post, options = {}, &block)
    product = post.product

    unless user_signed_in?
      return content_tag :div, options.merge(
        class: "#{options[:class]} tooltip tooltip-top",
        data: { tip: t("defaults.require_login") }
      ), &block
    end

    return if user_unpublish_post.present?

    return if product.posts.exists?(user_id: current_user.id)

    link_to new_post_path(product_id: product.id), options, &block
  end

  def show_new_post_button?(product)
    return true unless user_signed_in?

    !product.posts.exists?(user_id: current_user.id)
  end

  def show_unpublish_post_link?(user_unpublish_post)
    user_unpublish_post.present?
  end

  # 商品詳細の戻るボタン
  def back_to_list_path(product)
    if request.path.match?(/^\/categories\/[^\/]+\/products\/\d+/)
      category_path(product.category.slug)
    else
      products_path
    end
  end
end

app/views/products/_autocomplete_suggestions.html.erb
<% if @products.empty? %>
  <li class="w-full flex items-center py-2 px-3 text-sm border-b border-stone-200 last:border-b-0"
      role="presentation">
    <div class="flex flex-col">
    <span class="text-base-300"><%= t('defaults.message.no_product') %></span>
    <span class="text-stone-400/80"><%= t('defaults.message.search_suggestion') %></span>
    </div>
  </li>
<% else %>
  <% @products.each do |product| %>
    <li class="w-full flex items-center py-2 px-3 text-sm text-neutral hover:bg-stone-200 cursor-pointer border-b border-stone-200 last:border-b-0"
        role="option"
        data-autocomplete-value="<%= product.name %>"
        data-autocomplete-product-id="<%= product.id %>"
        data-autocomplete-product-url="<%= defined?(@category) && @category.present? ? category_product_path(@category.slug, product) : product_path(product) %>">
      <span><%= product.name %></span>
      <% if product.manufacturer.present? %>
        <span class="ml-2 text-base-300 text-xs"><%= product.manufacturer %></span>
      <% end %>
    </li>
  <% end %>
<% end %>

app/views/products/_bookmark.html.erb
<%= link_to bookmarks_path(product_id: product.id), 
            id: "bookmark-button-for-product-#{product.id}",
            data: { turbo_method: :post },
            class: "text-accent hover:text-hover" do %>
  <%= image_tag "bookmark.svg", class: "size-6 sm:size-7" %>
<% end %>

app/views/products/_bookmark_buttons.html.erb
<div class='mx-auto'>
  <% if current_user.bookmark?(product) %>
    <%= render 'products/unbookmark', { product: product } %>
  <% else %>
    <%= render 'products/bookmark', { product: product } %>
  <% end %>
</div>

app/views/products/_float_post_button.html.erb
<% if show_new_post_button?(@product) %>
  <div class="sm:hidden not-odd:fixed bottom-20 left-0 right-0 px-2 z-10 flex justify-center">
    <% if user_signed_in? %>
      <%= link_to new_post_path(product_id: @product.id),
          class: "floating_button py-4 px-10 sm:px-5 bg-info inline-flex gap-2 items-center justify-center" do %>
        <%= image_tag "cookie.svg", class: "size-7" %>
        <span class="text-base">
          <%= raw t('defaults.buttons.new_post') %>
        </span>
      <% end %>
    <% else %>
      <div class="floating_button bg-info py-4 px-10 sm:px-5 inline-flex gap-2 items-center justify-center tooltip tooltip-top"
          data-tip="<%= t('defaults.require_login') %>">
        <%= image_tag "cookie.svg", class: "size-7" %>
        <span class="text-base">
          <%= raw t('defaults.buttons.new_post') %>
        </span>
      </div>
    <% end %>
  </div>
<% end %>

app/views/products/_search_form.html.erb
<%= search_form_for @q,
      url: (@category.present? ? category_products_path(@category.slug) : products_path),
      method: :get,
      class: 'py-2 sm:py-0 sm:pb-1 flex justify-center w-full',
      data: { search_clear_target: "form" } do |f| %>

  <div class="bg-base-100 rounded-4xl py-2 px-0.5 md:p-6 max-w-md md:max-w-4xl mx-auto flex flex-col items-center">
    <div class="flex flex-row items-center gap-1 sm:gap-2 w-full">

      <div data-controller="autocomplete"
           data-autocomplete-url-value="<%= @category.present? ? category_products_autocomplete_path(@category&.slug) : autocomplete_products_path %>"
           role="combobox"
           class="relative w-full">

        <%= f.search_field :name_or_manufacturer_cont, 
            class: "flex-1 bg-white/80 rounded-xl ring-2 w-full md:w-100 ring-stone-300 text-base py-2 px-2 sm:px-4",
            placeholder: t('defaults.placeholders.search_products'),
            required: true,
            data: {
              search_clear_target: "input", 
              autocomplete_target: 'input',
            },
            aria: { autocomplete: "list" },
            autocomplete: "off" %>

        <ul class="list-group bg-white absolute top-full left-0 w-full md:text-sm z-10 shadow-lg rounded-md"
            data-autocomplete-target="results"></ul>
      </div>

      <%= button_tag type: "submit", class: "btn btn-secondary flex items-center justify-center" do %>
        <%= image_tag "magnifying-glass.svg", alt: t('helpers.submit.search'), class: "size-5 sm:size-6" %>
      <% end %>


      <% if @category.present? %>
        <button type="button"
                onclick="location.href='<%= category_path(@category.slug) %>'"
                class="btn">
         <%= image_tag "eraser.svg", alt: t('helpers.submit.clear'), class: "size-5 sm:size-6" %>
        </button>
      <% elsif controller_name == "categories" %>
        <button type="button"
                onclick="location.href='<%= categories_path %>'"
                class="btn">
          <%= image_tag "eraser.svg", alt: t('helpers.submit.clear'), class: "size-5 sm:size-6" %>
        </button>
      <% else %>
        <button type="button"
                onclick="location.href='<%= products_path %>'"
                class="btn">
          <%= image_tag "eraser.svg", alt: t('helpers.submit.clear'), class: "size-5 sm:size-6" %>
        </button>
      <% end %>

    </div>
  </div>
<% end %>

app/views/products/_unbookmark.html.erb
<%= link_to bookmark_path(current_user.bookmarks.find_by(product_id: product.id)),
            id: "unbookmark-button-for-product-#{product.id}",
            data: { turbo_method: :delete },
            class: "text-accent hover:text-hover" do %>
  <%= image_tag "bookmark-fill.svg", class: "h-7 w-7" %>
<% end %>

app/views/products/index.html.erb
<div class="p-1 sm:p-4 pb-24 sm:pb-4">
  <div class="flex flex-col p-1 lg:p-4 items-center justify-center w-full max-w-3xl mx-auto bg-base-100 rounded-4xl">
    <%= render "shared/product_list_header", title: t('.title') %>
    <%= render 'products/search_form', q: @q %>
    <%= render "shared/product_list", products: @products, category: @category, product_stats: @product_stats, pagy: @pagy %>
  </div>
</div>

<%= render "shared/product_register_button" %>

app/views/products/show.html.erb
<div class="p-1 sm:p-4 pb-16 sm:pb-4">
  <div class="flex flex-col p-1 lg:p-4 items-center justify-center w-full max-w-4xl mx-auto bg-base-100 rounded-4xl">
    <div class="relative w-full border-b border-base-200">
      <%= link_to back_to_list_path(@product),
        class: "absolute left-0 md:left-2 top-1/2 -translate-y-1/2 md:hover:bg-stone-200/80 duration-300 rounded-full p-2" do %>
        <%= image_tag "arrow-circle-left.svg", class: "h-7 w-7 sm:h-8 sm:w-8" %>
        </button>
      <% end %>
      <h1 class="text-center text-lg md:text-xl p-2 md:p-4">
        <%= t('products.show.title') %>
      </h1>
    </div>

    <div class="flex justify-center flex-row items-start w-full pb-2 sm:gap-4">
      <!-- 商品画像とURL -->
      <div class="flex flex-col items-center gap-6 sm:gap-2 shrink-0">

      <figure x-data="{ imageLoaded: false }"
              x-init="imageLoaded = $el.querySelector('img')?.complete || false">
        <div x-cloak x-show="!imageLoaded" class="flex animate-pulse space-x-4">
          <div class="pt-6 px-4 sm:p-4">
            <div class="size-25 sm:size-35 rounded-xl bg-stone-300"></div>
          </div>
        </div>
        <div x-show="imageLoaded" x-transition>
          <div class="pt-6 px-4 sm:p-4">
            <%= @product.decorate.product_image(
                  class: "size-25 sm:size-35 object-contain",
                  "@load" => "imageLoaded = true",
                  "@error"=> "imageLoaded = true"
                ) %>
          </div>
        </div>
      </figure>

      <% if @product.product_url.present? %>
        <%= link_to @product.product_url,
            target: "_blank",
            rel: "noopener noreferrer",
            class: "inline-flex items-start sm:items-center gap-1 underline text-sm text-secondary hover:opacity-80" do %>
          <%= image_tag "shopping-cart.svg", class: "h-6 w-6" %>
          <span><%= t('defaults.link.product_url') %></span>
        <% end %>
      <% end %>
    </div>

    <div class="relative flex flex-col justify-start items-center sm:items-start text-neutral pt-6 sm:py-4 md:px-0">
      <div class="flex flex-col items-center sm:items-start w-full">
        <div class="flex items-center pl-1 sm:pl-0 justify-between w-full">
          <div class="text-xs sm:text-sm text-base-300 max-w-sm pb-1">
            <%= @product.manufacturer %>
          </div>
          <% if user_signed_in? %>
            <div class="absolute top-1 right-0">
              <%= render 'bookmark_buttons', { product: @product } %>
            </div>
          <% end %>
        </div>
        <div class="text-sm md:text-lg px-1 sm:px-0 max-w-sm pt-1 pb-2 text-center sm:text-left">
          <%= @product.name %>
        </div>
      </div>

        <!-- あまピタカウント -->
        <div class="w-full sm:w-fit md:w-auto flex flex-col items-center justify-center md:block text-sm md:text-base pt-2">
          <% if @product.total_posts.zero? %>
            <div class="flex flex-row ring-stone-300/90 amapita-count-ring">
              <%= image_tag "smiley-blank.svg", class: "h-7 w-7 sm:h-8 sm:w-8" %>
              <%= t('defaults.label.no_rating') %>
            </div>
          <% else %>
            <div class="flex flex-col sm:flex-row ring-primary amapita-count-ring gap-1 sm:gap-2">
              <%= image_tag "smiley-wink.svg", class: "h-7 w-7 sm:h-8 sm:w-8" %>
              <p><%= t("defaults.label.stats", count: @product.total_posts, perfect:@product.perfect_sweetness_count) %></p>
            </div>
          <% end %>

          <!-- レビュー投稿ボタン -->
          <% if show_new_post_button?(@product) %>
            <div class="hidden sm:block text-center pt-4 sm:pt-6">
              <% if user_signed_in? %>
                <%= link_to new_post_path(product_id: @product.id),
                    class: "bg-info button-primary inline-flex items-center justify-center shadow-sm hover-animation gap-1" do %>
                  <%= image_tag "cookie.svg", class: "size-5 sm:size-6" %>
                  <span class="text-sm">
                    <%= t('defaults.buttons.new_post') %>
                  </span>
                <% end %>
              <% else %>
                <div class="bg-info button-primary inline-flex items-center justify-center shadow-sm hover-animation gap-1 tooltip tooltip-top"
                    data-tip="<%= t('defaults.require_login') %>">
                  <%= image_tag "cookie.svg", class: "size-5 sm:size-6" %>
                  <span class="text-sm">
                    <%= t('defaults.buttons.new_post') %>
                  </span>
                </div>
              <% end %>
            </div>
          <% end %>

          <!-- 非公開投稿の場合 -->
          <% if show_unpublish_post_link?(@user_unpublish_post) %>
            <div class="text-center pt-4">
              <%= link_to post_path(@user_unpublish_post),
                  class: "bg-success button-primary text-neutral inline-flex gap-2" do %>
                <%= image_tag "lock-key.svg", class: "h-5 w-5" %>
                <span class="text-sm">
                  <%= t('defaults.buttons.show_unpublished_post') %>
                </span>
              <% end %>
            </div>
          <% end %>
        </div>
      </div>
    </div>

    <% if @posts.present? %>
      <div class="flex flex-col justify-center lg:flex-row items-center lg:items-start p-2 sm:px-2 sm:py-2 gap-5 w-full">
        <!-- チャート -->
        <div class="flex justify-center w-full lg:w-3/5 max-w-md">
          <div class="w-full p-1 sm:p-4 border-secondary rounded-3xl bg-white/80 ring-2 ring-stone-200/50">
            <div class="flex justify-center pb-1 text-base md:text-lg">
              <%= t('defaults.sweetness_chart') %>
            </div>
            <div class="mx-auto w-full max-w-md p-2">
              <% if user_signed_in? && @user_post.present? %>
                <% if @posts.any?(&:user) && @posts.any? { |p| p.user != current_user } %>
                  <!-- ログインユーザーと他ユーザーの投稿がある場合 -->
                  <%= render "shared/chart/sweetness_average",
                    chart_id: "averageChart",
                    user_data: [
                      @user_post.post_sweetness_score.sweetness_strength,
                      @user_post.post_sweetness_score.aftertaste_clarity,
                      @user_post.post_sweetness_score.natural_sweetness,
                      @user_post.post_sweetness_score.coolness,
                      @user_post.post_sweetness_score.richness
                    ],
                    average_data: [
                      @average_scores[:sweetness_strength],
                      @average_scores[:aftertaste_clarity],
                      @average_scores[:natural_sweetness],
                      @average_scores[:coolness],
                      @average_scores[:richness]
                    ] %>
                <% else %>
                  <!-- ログインユーザーのみ投稿している場合 -->
                  <%= render "shared/chart/sweetness_posts",
                    chart_id: "radarChart",
                    data: [
                      @user_post.post_sweetness_score.sweetness_strength,
                      @user_post.post_sweetness_score.aftertaste_clarity,
                      @user_post.post_sweetness_score.natural_sweetness,
                      @user_post.post_sweetness_score.coolness,
                      @user_post.post_sweetness_score.richness
                    ] %>
                <% end %>
              <% else %>
                <!-- ログインユーザーは未投稿で他ユーザーの投稿がある場合 -->
                <%= render "shared/chart/sweetness_average_only",
                  chart_id: "averageChartOnly",
                  data: [
                    @average_scores[:sweetness_strength],
                    @average_scores[:aftertaste_clarity],
                    @average_scores[:natural_sweetness],
                    @average_scores[:coolness],
                    @average_scores[:richness]
                  ] %>
              <% end %>
            </div>
          </div>
        </div>

        <!-- ユーザーレビュー -->
        <div class="bg-white/80 ring-2 ring-stone-200/50 py-4 px-1 w-full lg:w-3/5 max-w-xl rounded-4xl flex flex-col items-center relative">
          <div class="p-1 text-base md:text-lg"><%= t('.review') %></div>

          <% @posts.each do |post| %>
          <div class="py-4 w-full border-b border-stone-200 last:border-b-0 relative">
            <div class="flex flex-col">

              <div class="flex flex-row gap-1 items-start">
                <!-- ユーザー情報 -->
                <div class="flex flex-col items-center p-1 w-24 shrink-0 gap-1">
                  <%= post.user.decorate.avatar_image(class: "w-10 h-10") %>
                  <span class="mt-1 text-xs text-start line-clamp-3 sm:line-clamp-2 mx-1"><%= post.user.name %></span>
                </div>

                <!-- 編集・削除・いいねボタン -->
                <% if user_signed_in? && current_user.own?(post) %>
                  <div class="dropdown dropdown-left dropdown-top absolute top-3 sm:top-4 right-0 sm:right-2 pt-2 z-10">
                    <div tabindex="0" role="button" class="rounded-xl bg-stone-100 ring-2 ring-base-200 duration-200 hover:brightness-96 p-1 sm:p-2">
                      <%= image_tag "pencil.svg", class: "size-5 shrink-0" %>
                    </div>

                    <ul tabindex="0" class="dropdown-content menu bg-base-100/90 rounded-box w-25 p-2 shadow-sm text-xs md:text-sm flex flex-col text-center gap-2">
                      <li>
                        <%= link_to edit_post_path(post), data: { turbo: false } do %>
                          <%= t('helpers.submit.edit') %>
                        <% end %>
                      </li>
                      <li>
                        <%= link_to post_path(post), class: "text-error",
                              data: { turbo_method: :delete, turbo_confirm: t('defaults.delete_confirm') } do %>
                          <%= t('helpers.submit.delete') %>
                        <% end %>
                      </li>
                    </ul>
                  </div>
                <% elsif user_signed_in? && !post.unpublish?  %>
                  <div class="absolute top-6 right-2 z-10">
                    <%= render 'posts/like_buttons', { post: post, button_id: "like-button-#{post.id}" } %>
                  </div>
                <% end %>

                <!-- 甘さ評価 + レビュー本文 -->
                <%= link_to post_path(post), class: "flex-1 min-w-0 flex flex-col gap-1 hover:opacity-70 transition-opacity duration-200" do %>
                  <% rating_images = { 
                      "lack_of_sweetness" => "smiley-meh.svg",
                      "could_be_sweeter" => "smiley-blank.svg",
                      "perfect_sweetness" => "smiley-wink.svg",
                      "slightly_too_sweet" => "smiley-nervous.svg",
                      "too_sweet" => "smiley-x-eyes.svg" 
                    } %>

                  <% bg_colors = { 
                      "lack_of_sweetness" => "bg-accent",
                      "could_be_sweeter" => "bg-accent",
                      "perfect_sweetness" => "bg-primary",
                      "slightly_too_sweet" => "bg-secondary",
                      "too_sweet" => "bg-secondary" 
                    } %>

                  <!-- 甘さ評価 -->
                  <div class="flex items-center justify-start rounded-xl gap-1 sm:gap-2 px-2 sm:px-4 py-2.5
                              text-neutral text-sm w-fit <%= bg_colors[post.sweetness_rating] %>">
                    <%= image_tag rating_images[post.sweetness_rating], class: "h-6 w-6 sm:h-7 sm:w-7 shrink-0" %>
                    <p class="truncate"><%= I18n.t("enums.post.sweetness_rating.#{post.sweetness_rating}") %></p>
                  </div>

                  <!-- レビュー -->
                  <% if post.review.present? %>
                    <div class="text-xs sm:text-sm text-neutral wrap-break-word pt-1 pb-3">
                      <p><%= truncate(post.review, length: 38, omission: '...') %></p>
                    </div>
                  <% end %>
                <% end %>
              </div>

              <div class="absolute bottom-2 right-2 text-xs text-base-200">
                <%= l post.created_at %>
              </div>
            </div>
          </div>
          <% end %>

          <div class="flex items-center justify-center p-4 w-full">
            <%== pagy_nav(@pagy) %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

<!-- 新規投稿 -->
<%= render "float_post_button" %>